### ISSUE TITLE
Error in buildXYData

### ISSUE THREAD

**Issue by sarah872** [hasaru-k/GlimmaV2#78] opened 2021-12-29 09:37 UTC
Hi!

I am getting an error when running `glimmaMA()`:
```
0 of 49 genes were filtered out in DESeq2 tests
Error in buildXYData(table, status, main, display.columns, anno, counts,  : 
  Length of groups must be equal to the number of columns in counts.
```

Here's my full code, I am starting with a counts table from `featureCounts`:

```
my_counts <- read.table("featurecounts.txt", header = TRUE, row.names=1)
my_counts$Chr <- NULL
my_counts$Start <- NULL
my_counts$End <- NULL
my_counts$Strand <- NULL
my_counts$Length <- NULL

my_columns=data.frame(row.names=as.vector(colnames(my_counts)), as.vector(colnames(my_counts)))
colnames(my_columns) = "treatment"
my_columns$treatment = substr(my_columns$treatment,1,nchar(my_columns$treatment)-1)
my_columns$treatment = as.factor(my_columns$treatment)

dds <- DESeqDataSetFromMatrix(countData=my_counts, colData = my_columns, design = ~0 + treatment)
DEanalysis <- DESeq(dds)
```

```
glimmaMDS(dds) # This works well
glimmaMA(DEanalysis) # This gives me the error
```

I'm attaching a subset of my `featurecounts.txt`.

**Comment by hasaru-k** [comment] 2022-12-08 11:18
Hey @sarah872! Sorry for the belated response - could you potentially attach a small subset of the data, so we could reproduce this 🙏

**Comment by hasaru-k** [comment] 2024-12-22 22:19
hey @sarah872, will close this since it's been a while - please feel free to reopen if this is still an issue

**Closed by hasaru-k** 2024-12-22 22:19 UTC
