### ISSUE TITLE
Rendering Glimma plots after knitting

### ISSUE THREAD

**Issue by joseale2310** [hasaru-k/GlimmaV2#77] opened 2021-11-17 15:41 UTC
Hi! 

I am trying to create an html report using knit from RStudio. The plot works completely fine in the Rmarkdown, but when trying to knit the document, the plot loses several features, like the table and count plot (although the document leaves the space necessary for the table). I can still hover the genes and check their values, but clicking does not do anything. 

![image](https://user-images.githubusercontent.com/9451832/142230976-dc7c43b0-1c0f-4dd5-ae26-708be0f26835.png)

These are my markdown options
```
--- 
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_format='all',
                        output_dir='./reports/')})
output:
  # To create PDF report, uncomment below
  #pdf_document:
  #  toc: yes
  html_document:
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float: yes
    df_print: paged
    dev: png
---
```

I am not sure if there is some option that I am missing or how I could recover all the functionality of the plot! Thank you!

**Comment by danphillips28** [comment] 2021-11-19 18:51
I am having the exact same issue for glimmaVolcano, eagerly awaiting a fix! 
Thanks,
Dan

**Comment by PeteHaitch** [comment] 2022-08-09 00:35
Can you create and provide a small example that reproduces the behaviour you're seeing?
Please also provide the output of `BiocManager::valid()` and your RStudio version.
That will really help people debug the issue.

**Comment by hasaru-k** [comment] 2022-12-08 11:14
Howdy @joseale2310 and @danphillips28,

I've managed to reproduce the issue with the markdown options you provided.

<img width="500" alt="Screen Shot 2022-12-08 at 10 06 35 pm" src="https://user-images.githubusercontent.com/35970468/206431743-22b933c0-13dd-4037-bee8-72406e3576fc.png">

It looks like Glimma's JS is interfering with the table of contents installation. Do the plots render if you disable the toc as below?

```
--- 
...
output:
  html_document:
    number_sections: yes
    theme: yeti
    # toc: yes
    # toc_float: yes
    df_print: paged
    dev: png
---
```

**Comment by hasaru-k** [comment] 2022-12-10 00:33
Yes, we're looking into a fix for this interaction as a priority

**Comment by hasaru-k** [comment] 2022-12-10 09:56
hey @joseale2310, I've pushed up a fix on a separate branch. Could you please try the following:

`remove.packages("Glimma")`

then:

`devtools::install_github("hasaru-k/GlimmaV2@hasaru-fixTocJqueryInteraction")`

And then try knitting a document with a Glimma plot. On my machine, this harmonises the interaction between the TOC installation and Glimma:

<img width="500" alt="Screenshot 2022-12-10 at 8 46 44 pm" src="https://user-images.githubusercontent.com/35970468/206845784-a689be75-bfa8-47ae-a9a0-f5b76526802e.png">

Please let me know if knitting Glimma plots with the `toc` + `toc_float` works after this. 

If so, we'll endeavour to merge this fix into the main branch (after doing some further testing, as the changes involve some rearranging and updating of dependencies, which have the potential to break things).

**Comment by joseale2310** [comment] 2022-12-19 20:53
Hi! 

Apologies for the delayed answer. I have been quite sick lately and then somehow I managed to delete my R environment. I have tried to use fix you set up there with the TOC activated. The interactive plot works fine but I cannot see the TOC at all.
It is somehow just a line.

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/9451832/208521191-299218ef-ee49-4c00-8984-9c856ee77899.png">

This is my session info:

```
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] edgeR_3.40.1                limma_3.54.0                DESeq2_1.38.2               SummarizedExperiment_1.28.0 Biobase_2.58.0             
 [6] MatrixGenerics_1.10.0       matrixStats_0.63.0          GenomicRanges_1.50.2        GenomeInfoDb_1.34.4         IRanges_2.32.0             
[11] S4Vectors_0.36.1            BiocGenerics_0.44.0         Glimma_2.3.2               

loaded via a namespace (and not attached):
 [1] bitops_1.0-7           fs_1.5.2               usethis_2.1.6          devtools_2.4.5         bit64_4.0.5            RColorBrewer_1.1-3    
 [7] httr_1.4.4             rprojroot_2.0.3        tools_4.2.2            profvis_0.3.7          utf8_1.2.2             R6_2.5.1              
[13] DBI_1.1.3              colorspace_2.0-3       urlchecker_1.0.1       withr_2.5.0            tidyselect_1.2.0       prettyunits_1.1.1     
[19] processx_3.8.0         bit_4.0.5              curl_4.3.3             compiler_4.2.2         cli_3.4.1              desc_1.4.2            
[25] DelayedArray_0.24.0    scales_1.2.1           callr_3.7.3            stringr_1.5.0          digest_0.6.31          rmarkdown_2.19        
[31] XVector_0.38.0         pkgconfig_2.0.3        htmltools_0.5.4        sessioninfo_1.2.2      highr_0.9              fastmap_1.1.0         
[37] htmlwidgets_1.6.0      rlang_1.0.6            rstudioapi_0.14        RSQLite_2.2.19         shiny_1.7.4            generics_0.1.3        
[43] jsonlite_1.8.4         BiocParallel_1.32.4    dplyr_1.0.10           RCurl_1.98-1.9         magrittr_2.0.3         GenomeInfoDbData_1.2.9
[49] Matrix_1.5-3           fansi_1.0.3            Rcpp_1.0.9             munsell_0.5.0          lifecycle_1.0.3        yaml_2.3.6            
[55] stringi_1.7.8          zlibbioc_1.44.0        pkgbuild_1.4.0         grid_4.2.2             blob_1.2.3             parallel_4.2.2        
[61] promises_1.2.0.1       crayon_1.5.2           miniUI_0.1.1.1         lattice_0.20-45        Biostrings_2.66.0      annotate_1.76.0       
[67] KEGGREST_1.38.0        locfit_1.5-9.6         knitr_1.41             ps_1.7.2               pillar_1.8.1           geneplotter_1.76.0    
[73] codetools_0.2-18       pkgload_1.3.2          XML_3.99-0.13          glue_1.6.2             evaluate_0.19          remotes_2.4.2         
[79] vctrs_0.5.1            png_0.1-8              httpuv_1.6.7           gtable_0.3.1           purrr_0.3.5            assertthat_0.2.1      
[85] cachem_1.0.6           ggplot2_3.4.0          xfun_0.35              mime_0.12              xtable_1.8-4           later_1.3.0           
[91] tibble_3.1.8           AnnotationDbi_1.60.0   memoise_2.0.1          ellipsis_0.3.2
```

Thanks for taking a look at it!

**Closed** 2024-01-22 12:52 UTC

**Comment by mei-du** [comment] 2024-03-12 04:20
Hi, thanks for this fix! 

I was having the same problem but following `devtools::install_github("hasaru-k/GlimmaV2@hasaru-fixTocJqueryInteraction")` my volcano plots work well when knitting my R Markdown documents. I host these as `workflowr` projects and deploy them as websites on GitLab. When viewing the websites in my browser (Google Chrome), I can save plots but I am unable to save the gene table with "Save Data" - when I click this button, "Save (0)" and "Save all" do not appear as usual, though I can do this when viewing the website through RStudio's Viewer.

I am using:
R 4.1.2
RStudio Server 2022.02.0 Build 443
Bioconductor 3.14
workflowr 1.7.1
rmarkdown 2.26
