### ISSUE TITLE
volcano plot got very slow in chrome with macbook 

### ISSUE THREAD

**Issue by axz91** [hasaru-k/GlimmaV2#79] opened 2022-03-08 16:43 UTC
yet no issue in windows

**Comment by hasaru-k** [comment] 2022-12-08 11:20
Hey there, could you please post a small example to help us reproduce this? This will help us debug cross-platform issues 🙏

**Comment by hasaru-k** [comment] 2024-12-22 22:19
hey @axz91, will close this since it's been a while - please feel free to reopen if it's still an issue

**Closed by hasaru-k** 2024-12-22 22:19 UTC
