### ISSUE TITLE
The y-axis of the exprContainer on the right side is not adjusting the minimal expression value

### ISSUE THREAD

**Issue by brunosa3** [hasaru-k/GlimmaV2#87] opened 2024-03-14 14:37 UTC
Thanks a lot for the great package you have created.

Currently, Im facing one issue on the y-axis of the exprContainer on the right side.

The scale of the y-axis is always kept at 0 and goes up to the maximal value of the samples. This behavior doesn t allow me to observe the differences between my group samples. How can I adjust the scale of the y-axis accordingly (e.g y-axis = [ min(value) - small number, max(value) + small number ]

the used code looks like this

`library(Glimma)

glimmaXY(x=data$logFC, y=-log10(data$adj.P.Val), 
         counts = exprs(eset), groups=pData(eset)$groups, status=data$Significance,
         anno = data %>% dplyr::select(ends_with("_Significance")),
         transform.counts = "logcpm",
         html = "res/comparison.html", width=1920 , height=1080)`

![image](https://github.com/hasaru-k/GlimmaV2/assets/43643787/b4fe34f7-1c45-4432-836e-816fc7d7bc90)

**Comment by danphillips28** [comment] 2024-04-06 16:26
Just came here to second that this would be a really nice feature (i.e. min_y_axis or automatic y scaling as well as/instead of max_y_axis). The usefulness of the expression plots (which I love) declines in proportion to the average expression of the chosen gene (because the points get crammed together at the top like shown above). Great package one of my favourites!

**Comment by tomsing1** [comment] 2024-05-21 18:51
👍 I would love to see this feature as well, it is the main reason I have to recreate plots for collaborators.

**Comment by hasaru-k** [comment] 2024-07-31 09:45
hi everyone, i've merged a feature allowing you to specify a custom Y min which should hopefully address the issue

please give it a go by reinstalling glimma using `devtools::install_github("hasaru-k/GlimmaV2")` and let me know if this resolves it :)

<img width="416" alt="Screenshot 2024-07-31 at 7 36 00 pm" src="https://github.com/user-attachments/assets/e607b268-6b13-423d-a543-b4624d6548fb">
<img width="418" alt="Screenshot 2024-07-31 at 7 36 19 pm" src="https://github.com/user-attachments/assets/631cc00e-d3c8-4e57-bc79-f702c84d71ce">

**Comment by tomsing1** [comment] 2024-07-31 15:44
Thank you so much @hasaru-k for implementing this fix! I can confirm that it works for me, too, e.g. with this example code shown below.

For some reason the `colorscheme` pulldown menu is not aligned with the Y-range input boxes on my system (both in the RStudio viewer as well as in google chrome).

This is great and will make my collaborators very happy 👍  

In case you are willing to tweak it a little bit, have you considered a range slider (with min and max values) instead of the numeric input boxes? 

```r
library(edgeR)
library(Glimma)
library(limma)

dge <- readRDS(
  system.file("RNAseq123/dge.rds", package = "Glimma"))
design <- readRDS(
  system.file("RNAseq123/design.rds", package = "Glimma"))
contr.matrix <- readRDS(
  system.file("RNAseq123/contr.matrix.rds", package = "Glimma"))

fit <- edgeR::voomLmFit(dge, design)
fit2 <- limma::contrasts.fit(fit, contrasts = contr.matrix)
fit2 <- limma::eBayes(fit2)
tt <- limma::topTable(fit2, number = Inf)
glimmaVolcano(fit2, dge = dge)
```
<img width="1279" alt="Screenshot 2024-07-31 at 8 38 49 AM" src="https://github.com/user-attachments/assets/3663a29a-8f25-4735-96cb-57a1b43ab3a7">

<details>
<summary>
Session Information
</summary>
R version 4.4.0 (2024-04-24)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] Glimma_2.3.2

loaded via a namespace (and not attached):
 [1] utf8_1.2.4                  renv_1.0.7                  SparseArray_1.4.8          
 [4] DESeq2_1.44.0               lattice_0.22-6              digest_0.6.36              
 [7] magrittr_2.0.3              grid_4.4.0                  fastmap_1.2.0              
[10] jsonlite_1.8.8              Matrix_1.7-0                GenomeInfoDb_1.40.1        
[13] limma_3.60.4                BiocManager_1.30.23         httr_1.4.7                 
[16] fansi_1.0.6                 UCSC.utils_1.0.0            scales_1.3.0               
[19] codetools_0.2-20            abind_1.4-5                 cli_3.6.3                  
[22] rlang_1.1.4                 crayon_1.5.3                XVector_0.44.0             
[25] Biobase_2.64.0              munsell_0.5.1               yaml_2.3.10                
[28] DelayedArray_0.30.1         S4Arrays_1.4.1              tools_4.4.0                
[31] parallel_4.4.0              BiocParallel_1.38.0         colorspace_2.1-1           
[34] ggplot2_3.5.1               locfit_1.5-9.10             GenomeInfoDbData_1.2.12    
[37] SummarizedExperiment_1.34.0 BiocGenerics_0.50.0         vctrs_0.6.5                
[40] R6_2.5.1                    matrixStats_1.3.0           stats4_4.4.0               
[43] lifecycle_1.0.4             zlibbioc_1.50.0             edgeR_4.2.1                
[46] S4Vectors_0.42.1            htmlwidgets_1.6.4           IRanges_2.38.1             
[49] pkgconfig_2.0.3             pillar_1.9.0                gtable_0.3.5               
[52] glue_1.7.0                  Rcpp_1.0.13                 statmod_1.5.0              
[55] tibble_3.2.1                GenomicRanges_1.56.1        MatrixGenerics_1.16.0      
[58] htmltools_0.5.8.1           compiler_4.4.0     
</details>

**Comment by hasaru-k** [comment] 2024-08-05 01:03
hey @tomsing1,

After your suggestion I explored using range sliders and ran into some difficulties defining a `max` attribute for the max slider which is a required field. I didn't want to limit users to some arbitrarily defined Y max (e.g. 10 or 100 times the highest plotted point). A similar problem emerges for the minimum slider. The number input allows us to avoid this issue since there is no upper limit for the max value (and no lower limit for the min value).

Thanks for pointing out the CSS issue with `colourscheme`, I think I have resolved this - could you please reinstall with `devtools::install_github("hasaru-k/GlimmaV2@addMinYAxis")` and take a look?

**Comment by tomsing1** [comment] 2024-08-05 16:37
Thanks a lot for exploring the range slider idea, @hasaru-k ! I hadn't considered the choice of the `max` attribute. The current solution (number input) work, and its solves the problem 👍 

The `colourscheme` menu is now aligned with the `Y min` and `Y max` boxes when I run it  as well. 
Many thanks!

**Comment by hasaru-k** [comment] 2024-08-05 21:39
glad to hear it @tomsing1 🎉 will mark this issue as closed

**Comment by hasaru-k** [comment] 2024-12-06 19:37
hey @brunosa3, just to confirm are you able to see the `Y min` box in your plots? Would be great if you could attach a screenshot of the affected plots

**Comment by brunosa3** [comment] 2024-12-06 20:32
Hey @hasaru-k 
Yes it’s working now for me too. I’m sorry for not coming back to you earlier. Though it would be nice if it would be possible to change the y axis independent of the expression levels. 
I had a few times the situation that a certain gene had a few samples that were super low expressed but the majority of samples across conditions were at higher levels. This made it very difficult to see the difference between the conditions due to the scale. In such cases it would be nice to exclude these points by adjusting the y axis.

Anyway I guess you can close this thread. 

I’m really happy about your work. thanks a lot. I really appreciate it. For the future it would be awesome if you could add some ijter in the scatter plot on the top right as it was set up in the older version for better visualisation.

cheers

**Comment by hasaru-k** [comment] 2024-12-06 23:10
no problem, thank you for the helpful suggestions @brunosa3!

**Closed by hasaru-k** 2024-12-06 23:10 UTC
